### PR TITLE
Enable user to requests for payment

### LINKED ISSUE #102: Payment Requests
#### Motivation / Context

Currently, the `perun-node` supports only decreasing a user's balance when sending a payment channel update. The user is not allowed to request payments (increase his/her balance and decrease the peer's balance). 

Since counter signatures are required for each channel update, it should be safe to enable payment requests.

#### Description

Payment app in `go-perun` limits the user to only decrease (and not increase) his/her balance when sending payment channel updates. It is implemented to demonstrate the use of `ActorIndex` for validating an off-chain state update. 

However, in the payment app of `perun-node`, we need to enable the user to both increase as well as decrease his balance when sending a off-chain state update. The only check required in this case is to ensure, the sum of balances in the channel remains constant and this is done by the generic valid transition function of the state machine. Also, for the payment app, we do not need the concept of on-chain progression. 
Hence use a `NilApp` in the channel and test to ensure payment requests is working.
 

##### Relates to
Depends on https://github.com/hyperledger-labs/perun-node/issues/101

#### Testing

1. Add a new test for payment request in integration test of  `gRPC` package.

#### Thread Safety

Send channel update is already thread safe, the property should be retained.

### PR DESCRIPTION
**Pull request by anagha-ks**
#### Description
Support payment requests which means user is allowed to request payment from  peer so that user's balance will increase and the peer's balance will decrease.
##### Category

Improvement 

##### Relevant issue
Closes #102

#### Testing
Added test in `Test_Integ_Role` in `api/grpc` to check if payment request is working. All existing tests should pass including the added one.

##### Steps to run the tests

1.From `api/grpc` run `go test -tags=integration -count=1 -cover -run Test_Integ_Role -v`
2. 
3.  

#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

### CODE REVIEW

**Comment by manoranjith** [comment]
You can remove the `init()` function(in this [file](https://github.com/hyperledger-labs/perun-node/blob/f8ce1554cb63a1c3c995a2ce7aa98ab540cbff31/session/role_integ_test.go)), that initializes the payment app in go-perun, as it is not needed anymore.

If that is removed, then the following integration test is failing, 

```
Test_Integ_Persistence/GetChannelInfos/happy: session_integ_test.go:160: 
        	Error Trace:	session_integ_test.go:160
        	Error:      	Not equal: 
        	            	expected: 3
        	            	actual  : 0
        	Test:       	Test_Integ_Persistence/GetChannelInfos/happy
```

Could you make remove the init part and see why this test is failing ?

**Comment by manoranjith** [comment]
@anagha-ks I have removed the mentioned init functions related to `ppayment` package. This caused the `Test_Integ_Persistence/GetChannelInfos/happy` test in  `session` package to fail. It was because the database directory used in the persistence test had channels created using "ppayment app" and hence the channels are not restored when we are not initializing the "ppayment app" in go-perun.

To fix this, i created the testdata again by opening three channels and closing the session with "force" option after removing the mentioned init function. If i use this database directory in persistence tests, the channels are restored (as they also were created using nil app) and all tests are passing.

**Comment by manoranjith** [comment]
@anagha-ks  Can you review the whole thing once and confirm if it is ready to be merged ?

**Comment by manoranjith** [comment]
Also, I have updated the persistence tests to copy the database dir to tmp directory before using it, so that the files in project directory are not modified.

**Comment by anagha-ks** [comment]
> Also, I have updated the persistence tests to copy the database dir to tmp directory before using it, so that the files in project directory are not modified.

Looks fine. This can be merged now.

**Review by manoranjith — APPROVED** [review]

**Pull request merged**
