### PR TITLE
Use random nonce in new channel proposal

### PR DESCRIPTION
**Pull request by anagha-ks**
#### Description
Feature to use shared nonce was added in go-perun in this [commit](https://github.com/hyperledger-labs/go-perun/commit/ba500c4ec66481043dfd0b89be170023ef7fa11a). But this was missing some changes, which were added later in this [commit](https://github.com/hyperledger-labs/go-perun/commit/27be1b2016bd19bda0b7e9d0ec42ef5df4f903ac).This PR is part 1/2, which will set nonce in the channel proposal.

##### Category

Improvement 

##### Relevant issue
Relates to https://github.com/hyperledger-labs/perun-node/issues/101

#### Testing
All existing tests are passing

#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

### CODE REVIEW

**Review by manoranjith — CHANGES_REQUESTED** [review]
I notice that, this PR adds two changes,

1. Updating `perun-node` to adopt the change in go-perun API `pchannel.UpdateBy`
2. Using the newly added random nonce option in go-perun.

Can you split these two changes into two separate commits ?

**Comment by manoranjith** [comment]
Random nonce was used in new channel proposal before this commit as well, but it was generated by a function defined in `perun-node` itself. With this commit, the newly added option in `go-perun` is used instead.

Could you also update the commit message to reflect this ?

**Review by manoranjith — CHANGES_REQUESTED** [review]
For this commit to build, should the version of `go-perun` in `go.mod` also be updated ?

**Comment by anagha-ks** [comment]
> For this commit to build, should the version of `go-perun` in `go.mod` also be updated ?

Yes. updated in this [commit](https://github.com/hyperledger-labs/perun-node/pull/109/commits/b119f2a2ab26c82eb966845350b07af1fab25ac0)

**Comment by anagha-ks** [comment]
> Random nonce was used in new channel proposal before this commit as well, but it was generated by a function defined in `perun-node` itself. With this commit, the newly added option in `go-perun` is used instead.
> 
> Could you also update the commit message to reflect this ?

Addressed in this [commit](https://github.com/hyperledger-labs/perun-node/pull/109/commits/711ab5423fe5644cfdb17a47fda930816663a266)

**Comment by anagha-ks** [comment]
> I notice that, this PR adds two changes,
> 
>     1. Updating `perun-node` to adopt the change in go-perun API `pchannel.UpdateBy`
> 
>     2. Using the newly added random nonce option in go-perun.
> 
> 
> Can you split these two changes into two separate commits ?
 I have split in to 2 commits. One to get the [Updateby](https://github.com/hyperledger-labs/perun-node/pull/109/commits/b119f2a2ab26c82eb966845350b07af1fab25ac0) change and the other one to use [random nonce](https://github.com/hyperledger-labs/perun-node/pull/109/commits/711ab5423fe5644cfdb17a47fda930816663a266) in channel proposal

**Review by manoranjith — APPROVED** [review]

**Pull request merged**
