### PR TITLE
Add readme for perunnodetui

### PR DESCRIPTION
**Pull request by manoranjith**
#### Description

- Containes a brief tutorial on how to use the tui client.

##### Category

Implementation Task 

#### Testing

No modifications in code.

##### Steps to run the tests

1. 
2. 
3.  

#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

### CODE REVIEW

**Comment by danielksan81** [comment]
@manoranjith Does it make sense to add a picture which is showing the running terminals as a first impression?

**Comment by manoranjith** [comment]
Yeah.... I think it make it better

I will update the PR

**Comment by manoranjith** [comment]
I have included an image now. @danielksan81

**Review by danielksan81 — APPROVED** [review]
lgtm

**Pull request merged**
